### ISSUE TITLE
Miss detect at Test::Requires::Scanner::Constants

### ISSUE THREAD

**Issue by Songmu** [moznion/Perl-PrereqScanner-Lite#3]
```
[Songmu]$ perl -ML -MYAML -E 'warn Dump( Perl::PrereqScanner::Lite->new->scan_module("Test::Requires::Scanner::Constants") )'
--- !!perl/hash:CPAN::Meta::Requirements
bad_version_hook: ~
requirements:
  Compiler::Lexer::Constants: !!perl/hash:CPAN::Meta::Requirements::_Range::Range
    minimum: !!perl/hash:version
      original: 0
      version:
        - 0
  Const::CommonCompiler::Lexer::TokenType::T_NamespaceResolverCompiler::Lexer::TokenType::T_NamespaceCompiler::Lexer::TokenType::T_SemiColonCompiler::Lexer::TokenType::T_UseDeclCompiler::Lexer::TokenType::T_UsedNameCompiler::Lexer::TokenType::T_RegListCompiler::Lexer::TokenType::T_RegExpCompiler::Lexer::TokenType::T_StringCompiler::Lexer::TokenType::T_RawStringCompiler::Lexer::TokenType::T_VersionStringCompiler::Lexer::TokenType::T_IntCompiler::Lexer::TokenType::T_DoubleCompiler::Lexer::TokenType::T_KeyCompiler::Lexer::TokenType::T_WhiteSpaceCompiler::Lexer::TokenType::T_LeftParenthesisCompiler::Lexer::TokenType::T_RightParenthesisCompiler::Lexer::TokenType::T_LeftBraceCompiler::Lexer::TokenType::T_RightBrace: !!perl/hash:CPAN::Meta::Requirements::_Range::Range
    minimum: !!perl/hash:version
      original: 0
      version:
        - 0
  strict: !!perl/hash:CPAN::Meta::Requirements::_Range::Range
    minimum: !!perl/hash:version
      original: 0
      version:
        - 0
  warnings: !!perl/hash:CPAN::Meta::Requirements::_Range::Range
    minimum: !!perl/hash:version
      original: 0
      version:
        - 0
```

I think this problem caused by Const::Common.
